config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  resources :links
  get ":short_url", to: "links#show"
  get "shortened/:short_url", to: "links#shortened", as: :shortened
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :full_url, presence: true, on: :create
  validates :full_url, :format => URI::regexp(%w(http https www))
  before_create :generate_short_url
  
  # Assign a short url
  def generate_short_url
    
    # Generate 3 arrays with lowercase, upper case and nums
    lower = ('a'..'z').to_a
    upper = ('A'..'Z').to_a
    num = ('0'..'9').to_a
    letters = lower.concat(upper)
    chars = letters.concat(num)

    # Get last short_url in db 
    # If there is none, then start the short_url at 'a'
    if Link.last == nil
      last_short_url = "a"
      short_char = 0
    else

      # Grab last digit of short_url from last short url to account for double digit URLs
      last_short_url = Link.last.short_url[-1]

      # Add 1 to get the next index in the array and set the new short url
      short_char = chars.find_index(last_short_url) + 1
    end
    link = Link.find_by_short_url(chars[short_char])
    if link.nil? && short_char <= 61
      self.short_url = chars[short_char]
    else
      shuffled_chars = chars.shuffle[0,2].join
      self.short_url = shuffled_chars
    end
  end

  def find_duplicate
    Link.find_by_sanitized_url(self.sanitized_url)
  end

  def sanitize
    self.full_url.strip!

    # Remove http://, https://, www and any trailing /
    self.sanitized_url = self.full_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
    self.sanitized_url.slice!(-1) if self.sanitized_url.last == "/"
    self.sanitized_url = "http://#{self.sanitized_url}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :shortened]
  
  def index
    @link = Link.new
    @links = Link.order(clicks: :desc).first(100)
  end

  def show
    @link.clicks += 1
    @link.save
    redirect_to @link.sanitized_url
  end

  def create
    @link = Link.new(link_params)
    @links = Link.all
    @link.sanitize
    if @link.find_duplicate.nil? 
      if @link.save
        @link.clicks += 1
        @link.save
        redirect_to shortened_path(@link.short_url)
        # TODO: Allow the user to see the short link populate on the same page

      else

        # TODO: Flash messages pop up on reload
        flash[:notice] = "There was an error with your link, read the message below:"
        render :index
      end
    else

      # TODO: should a click be added here?
      flash[:notice] = "A short link already exsists for this URL, search the 'Top 100' table below:"
      render :index
    end
  end

  private

  def set_link
    @link = Link.find_by_short_url(params[:short_url])
  end

  def link_params
    params.require(:link).permit(:full_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Mini URL</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<div class="jumbotron">
  <%= image_tag("shorty.png") %>
  <style>
  .jumbotron { 
      background-color: #efe15b;  /*Cream*/ 
      color: #D67C73;
      height: 460px;
  }
  </style>
  <div class="header-title">
    <h2>Shorty shrinks links</h2> 
  </div>
  <br>
  <br>
  <br>
  
</div>
<%= yield %>
<footer class="container-fluid bg-4 text-center">
  <p>&copy; 2017 Developed by <a href="https://medium.com/@laniberry">Lani Berry</a></i></a></p> 
</footer>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, :html=>{:class=> "form-inline search"}) do |f| %>
  <div class="input-group">
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:
        <% @link.errors.full_messages.each do |message| %>
          <%= message %></p>
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="field">
      <div class="input-group"> 
        <%= f.text_field :full_url, placeholder: "Paste your link here", class: 'form-control', size: "50" %>
        <div class="input-group-btn">
          <%= f.submit "Shrink", class: "btn btn-success" %>
        </div>
      </div>
    </div>
<% end %>
</div>

 <% if notice %>
    <div id="notice_wrapper">
      <p class="notice"><%= notice %></p>
    </div>
  <% elsif alert %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>    
      </div>
  <% end %>

<script>
  $(document).ready(function() {
      setTimeout(function() {
          $('#notice_wrapper').fadeOut("slow", function() {
              $(this).remove();
          });
      }, 4500);
  });
</script>

app/views/links/_table.html.erb
<div class="container-fluid">
  <div class="leaderboard-title">
    <h1>Top 100</h1>
  </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Rank</th>
          <th>Full URL</th>
          <th>Short URL</th>
          <th>Amount Visited</th>
        </tr>
      </thead>
      
      <tbody>
        <% @links.each_with_index do |link, i| %>
          <% shortened_url = "https://mini-u.herokuapp.com/#{link.short_url}" %>
          <tr>   
            <td><%= (i+1).ordinalize %></td>
            <td><%= link.full_url %></td>
            <td><%= link_to shortened_url, shortened_url, target: "blank" %></td>
            <td>
            <%= link.clicks %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>  

app/views/links/index.html.erb
<%= render 'form' %>
<%= render 'table' %>

app/views/links/shortened.html.erb
<% shortened_url = "https://mini-u.herokuapp.com/#{@link.short_url}" %>

<div class="shorty">
  <h2>Here's your shorty url: <%= link_to shortened_url, shortened_url, target: "blank" %> </h2>
</div>

<div class="back-btn">
  <%= link_to "Go Back", links_path, class: 'btn btn-success' %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>